# Generated by Django 4.1.7 on 2023-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('sub', models.CharField(max_length=220)),
                ('msg', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
